<?php

/**
 * @file
 * Contains dom_news.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dom_news_form_node_news_form_alter(&$form, FormStateInterface $form_state) {
  dom_news_news_form_alter($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dom_news_form_node_news_edit_form_alter(&$form, FormStateInterface $form_state) {
  dom_news_news_form_alter($form, $form_state);
}

/**
 * Helper function to alter news form.
 */
function dom_news_news_form_alter(&$form, FormStateInterface $form_state) {
  $entity_manager = \Drupal::entityTypeManager();

  if (array_key_exists('template', $form)) {
    $images = [];
    foreach ($form['template']['widget']['#options'] as $option => $name) {
      /** @var \Drupal\taxonomy\Entity\Term $term */
      if ($term = $entity_manager->getStorage('taxonomy_term')->load($option)) {
        if ($term->hasField('template_image') && !$term->get('template_image')->isEmpty()) {
          /** @var \Drupal\media\Entity\Media $media */
          $media = $term->get('template_image')->entity;
          if ($media->hasField('news_image') && !$media->get('news_image')->isEmpty()) {
            /** @var \Drupal\file\Entity\File $image */
            $image = $media->get('news_image')->entity;
            $images[$option] = $image->url();
          }
        }
      }
    }

    $form['#attached']['drupalSettings']['newsImages'] = $images;
    $form['#attached']['library'][] = 'dom_news/news';
  }
}
